name: PlayWall
version: 6.1.0
build: 38
identifier: de.tobias.playpad.v6
main: de.tobias.playpad.PlayPadMain
author: Tobias Ullerich
backup: false
iconPath: icon
updateURL: https://tobisan.ddns.net/playwall/resources/executables
userInfo:
  Website: http://tobisan.no-ip.org/
  ErrorURL: http://tobisan.no-ip.org/upload.php
  PluginsURL: 
     Stable: https://tobisan.ddns.net/playwall/resources/executables/stable/plugins.yml
     Beta: https://tobisan.ddns.net/playwall/resources/executables/beta/plugins.yml
  ChangelogURL: https://tobisan.ddns.net/roadmap/php/index.php?id=1
  UpdaterProgram: https://tobisan.ddns.net/playwall/resources/executables/utils/
