name: PlayWall
version: 5.0.0
build: 27
identifier: de.tobias.playpad
main: de.tobias.playpad.PlayPadMain
author: Tobias Ullerich
backup: false
iconPath: icon
updateURL: http://tobisan.no-ip.org/files/PlayWall
userInfo:
  Website: http://tobisan.no-ip.org/
  ErrorURL: http://tobisan.no-ip.org/upload.php
  PluginsURL: http://tobisan.no-ip.org/files/PlayWall/plugins.yml
  ChangelogURL: http://tobisan.no-ip.org/whatsnew-2.php?id=1
  UpdaterProgram: http://tobisan.no-ip.org/files/Updater/
