name: PlayWall
version: 6.2.0
build: 40
identifier: de.tobias.playpad.v7
main: de.tobias.playpad.PlayPadMain
author: Tobias Ullerich
backup: false
iconPath: icon
updateURL: https://tobisan.thecodelabs.de/playwall/resources/executables
userInfo:
  Website: http://tobisan.thecodelabs.de/playwall/
  PluginsURL:
     Stable: https://tobisan.thecodelabs.de/playwall/resources/executables/stable/plugins.yml
     Beta: https://tobisan.thecodelabs.de/playwall/resources/executables/beta/plugins.yml
  ChangelogURL: https://tobisan.thecodelabs.de/roadmap/php/index.php?id=1
  UpdaterProgram: https://tobisan.thecodelabs.de/playwall/resources/executables/utils/
  Server: tobisan.thecodelabs.de:8090
  AccountRegister: http://tobisan.thecodelabs.de/playwall/php/index.php
