name: PlayWall
version: 6.2.0
build: 40
identifier: de.tobias.playpad.v7
main: de.tobias.playpad.PlayPadMain
author: Tobias Ullerich
backup: false
iconPath: icon
updateURL: https://tobisan.ddns.net/playwall/resources/executables
userInfo:
  Website: http://tobisan.no-ip.org/
  PluginsURL:
     Stable: https://tobisan.ddns.net/playwall/resources/executables/stable/plugins.yml
     Beta: https://tobisan.ddns.net/playwall/resources/executables/beta/plugins.yml
  ChangelogURL: https://tobisan.ddns.net/roadmap/php/index.php?id=1
  UpdaterProgram: https://tobisan.ddns.net/playwall/resources/executables/utils/
  Server: tobisan.ddns.net:8090
