/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_playpad_Waveform */

#ifndef _Included_de_tobias_playpad_Waveform
#define _Included_de_tobias_playpad_Waveform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_playpad_Waveform
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_Waveform_initialize
  (JNIEnv *, jclass);

/*
 * Class:     de_tobias_playpad_Waveform
 * Method:    createWaveform
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_Waveform_createWaveform
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
