/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_playpad_audio_mac_AVAudioPlayerBridge */

#ifndef _Included_de_tobias_playpad_audio_mac_AVAudioPlayerBridge
#define _Included_de_tobias_playpad_audio_mac_AVAudioPlayerBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_initialize
  (JNIEnv *, jclass);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_init
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_play
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    isPlaying
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_isPlaying
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_pause
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_stop
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    seek
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_seek
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    setLoop
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_setLoop
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    getVolume
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_getVolume
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    setVolume
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_setVolume
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    load
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_dispose
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    getDuration
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_getDuration
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    getPosition
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_getPosition
  (JNIEnv *, jobject);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    setRate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_setRate
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    getAudioDevices
 * Signature: ()[Lde/tobias/playpad/audio/mac/AudioDevice;
 */
JNIEXPORT jobjectArray JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_getAudioDevices
  (JNIEnv *, jclass);

/*
 * Class:     de_tobias_playpad_audio_mac_AVAudioPlayerBridge
 * Method:    setCurrentAudioDevice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_audio_mac_AVAudioPlayerBridge_setCurrentAudioDevice
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
