/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_tobias_playpad_NativeAudio */

#ifndef _Included_de_tobias_playpad_NativeAudio
#define _Included_de_tobias_playpad_NativeAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_NativeAudio_initialize
  (JNIEnv *, jclass);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    play
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_NativeAudio_play
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    pause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_NativeAudio_pause
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_NativeAudio_stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    seek
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_NativeAudio_seek
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    setLoop
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_NativeAudio_setLoop
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    getVolume
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_de_tobias_playpad_NativeAudio_getVolume
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    setVolume
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_NativeAudio_setVolume
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    load
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_tobias_playpad_NativeAudio_load
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    dispose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_NativeAudio_dispose
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    getDuration
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_de_tobias_playpad_NativeAudio_getDuration
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    getPosition
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_de_tobias_playpad_NativeAudio_getPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_tobias_playpad_NativeAudio
 * Method:    setRate
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_de_tobias_playpad_NativeAudio_setRate
  (JNIEnv *, jclass, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
