name: "PlayWall"
version: "6.2.0"
build: 40
identifier: "de.tobias.playpad.v7"
date: "2019-02-04"

main: "de.tobias.playpad.PlayPadMain"
author: "Tobias Ullerich"

basePath: "PlayWall"

serverBaseURL: "https://playwall.thecodelabs.de/files"

userInfo:
  Website: "https://playwall.thecodelabs.de/"
  Repository: "https://thecodelabs.de/PlayWall/PlayWallDesktop"
  ChangelogURL: "https://playwall.thecodelabs.de/php/roadmap.php"
  Server: "playwall.thecodelabs.de:8090"
  AccountRegister: "https://playwall.thecodelabs.de/php/index.php"
