name: "PlayWall"
version: "${project.version}"
build: ${project.build.code}
identifier: "de.tobias.playpad.v7"
date: "${project.versionDate}"

main: "de.tobias.playpad.PlayPadMain"
author: "Tobias Ullerich"

basePath: "PlayWall"

serverBaseURL: "https://playwall.thecodelabs.de/files"

userInfo:
  website: "https://playwall.thecodelabs.de/"
  repository: "https://thecodelabs.de/PlayWall/PlayWallDesktop"
  changelogURL: "https://playwall.thecodelabs.de/php/roadmap.php"
  server: "playwall.thecodelabs.de:8090"
  accountRegister: "https://playwall.thecodelabs.de/php/index.php"
